### ISSUE TITLE
Add border to table cells

### ISSUE THREAD

**Issue by ajitdev** [drupalpune/campsite#170]
Adding border to `td` would make the sponsors page look good.

This should do:

```css
td {
    border: 1px solid;
    padding: 10px;
}
```

Before:
![image](https://github.com/user-attachments/assets/c62c96b9-29ab-4922-abbb-84eaf36a8285)

After:
![image](https://github.com/user-attachments/assets/651de05f-36f5-4797-9ff5-059f47705ed8)
